### ISSUE TITLE
[1.0.0] TODO list

### ISSUE THREAD

**Issue by Misat11** [ScreamingSandals/BungeeLink#1]
* [ ] If BungeeLink on Proxy is not accessible, make sure the plugin will wait for proxy plugin instead of failing.
* [ ] If BungeeLink proxy is unreachable don't allow new players.
* [ ] Customizable server selector (maybe just add some api and release wiki how hook this plugin into SimpleInventories)
* [ ] Make an API for Players and make Players Contactable (so Custom payload could be send to specific player)
* [ ] Improve console messages and remove messages that don't have any sence.
* [ ] Fabric support (plugin should depends on https://www.curseforge.com/minecraft/mc-mods/fabricproxy)
* [ ] Forge support
* [ ] Sponge support (Sponge for Java 11 aka sponge 8 is needed before implementing this)
